project:
  type: book
  output-dir: docs

book:
  title:    "Statistical Inference"
  subtitle: "A Gentle but Critical Introduction to Statistical Inference, Moderation, and Mediation"
  author:   ["Wouter de Nooy","et al."]
  date:     now
  search:   true
  page-navigation: true
  repo-url: https://github.com/ShKlinkenberg/Statistical-Inference
  repo-actions: [issue, source, edit]
  chapters:
    - index.qmd
    - 01-samplingdistr.qmd
    - 02-probability.qmd
    - 03-estimation.qmd
    - 04-hypothesis.qmd
    - 07-anova.qmd
    - 08-moderation-categorical.qmd
    - 09-moderation-continuous.qmd
    - 10-confounding.qmd
    - 11-mediation.qmd
    - 12-Appendix.qmd
    - 13-colophon.qmd
    - 14-references.qmd
  sidebar:
    style: "docked"

bibliography: RefList.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
    toc-location: right
    css: styleX.css
  # pdf:
  #   documentclass: scrreprt

number-depth: 4

# Define custom cross-references for embedded videos

crossref:
  custom:
    - key: vid
      kind: float
      reference-prefix: Video