project:
  type: book
  output-dir: docs

book:
  title:    "Statistical Inference"
  subtitle: "A Gentle but Critical Introduction to Statistical Inference, Moderation, and Mediation"
  author:   ["Wouter de Nooy","et al."]
  date:     now
  search:   true
  repo-url: https://github.com/ShKlinkenberg/Statistical-Inference
  repo-actions: [edit]
  chapters:
    - index.qmd
    # - 01-samplingdistr.qmd
  sidebar:
    style: "docked"

bibliography: RefList.bib

format:
  html:
    theme: cosmo
    link-external-newwindow: true
  # pdf:
  #   documentclass: scrreprt

number-depth: 4