---
title: "Statitstical Inference"
subtitle: "A Gentle but Critical Introduction to Statistical Inference, Moderation, and Mediation"
author: ["Wouter de Nooy","et al."]
date: "2016-09-20 - `r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    css: styleX.css
    number_sections : TRUE
    split_by : "section+number"
    split_bib: FALSE
    download: ["GentleIntro.pdf"]
    highlight: monochrome
    config:
      toc:
        collapse: section
      sharing: no
    includes:
#      in_header: hypothesis.html
#   bookdown::pdf_book:
#     keep_tex: yes
#     toc : TRUE
#     toc_depth : 3
#     toc_unnumbered : yes
#     number_sections : TRUE
#     highlight: monochrome
#     includes: 
#       in_header: preambleX.tex
#       before_body: lists.tex
# documentclass: book
# geometry: left=40mm, right=30mm, top=30mm, bottom = 25mm
bibliography: ["RefList.bib"]
biblio-style: "apa"
csl: apa.csl
link-citations: TRUE
---

# Introduction and Reader's Guide {-}

This book offers a non-technical but thorough introduction to statistical inference. It discusses a minimal set of concepts needed to understand both the possibilities and pitfalls of estimation, null hypothesis testing, moderation, and mediation analysis. It uses a minimum of formal notation.

### Intended Audience and Setting {-}

This book is written as reading material for a follow-up course in statistics, in the bachelor of Communication Science at the University of Amsterdam. Students enrolled in this course have passed an introductory course in statistics that explained how to change research questions into variables and associations between variables, how to select and execute the correct analysis or test (in SPSS) to answer their research question, and how to interpret the results in a language that is both comprehensible for the average reader and complying with professional standards (APA standard for reporting test results). In addition, they have learned the very basics of inferential statistics: How to decide which null hypothesis to reject based on reported _p_ values, and how to interpret confidence intervals.  

This book is meant for use in a flipped-classroom setting. Students should read the text, watch embedded videos, and play with the interactive content before they meet in class. Class meetings are used to answer questions raised by the students, do group work to exercise with the concepts and techniques presented in the text, and do short tests to check understanding.  

### Interactive Content {-}

The interactive content in this book replaces simulations that used to be demonstrated during lectures. I expect that doing simulations yourself rather than watching them being done by someone else enhances understanding. I have tried to break down the simulations into smaller steps, confronting the student several times with essentially the same simulation, but with added complexity. I hope that this approach enhances understanding and remembrance and, at the same time, avoids frustration caused by complex dashboards offering all options at once.