<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.45">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Mediation with Regression Analysis – Statistical Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./12-Appendix.html" rel="next">
<link href="./10-confounding.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/vis-9.1.0/vis-network.min.css" rel="stylesheet">
<script src="site_libs/vis-9.1.0/vis-network.min.js"></script>
<script src="site_libs/visNetwork-binding-2.1.2/visNetwork.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styleX.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./11-mediation.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mediation with Regression Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Inference</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ShKlinkenberg/Statistical-Inference" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction and Reader’s Guide</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-samplingdistr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Sampling Distribution</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Probability Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estimating a Parameter</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Moderation with Analysis of Variance (ANOVA)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-moderation-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regression Analysis And A Categorical Moderator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-moderation-continuous.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Regression Analysis With A Numerical Moderator</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-confounding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Analysis And Confounders</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-mediation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mediation with Regression Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-colophon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Colophon</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#mediation-as-causal-process" id="toc-mediation-as-causal-process" class="nav-link" data-scroll-target="#mediation-as-causal-process"><span class="header-section-number">9.1</span> Mediation as Causal Process</a>
  <ul class="collapse">
  <li><a href="#sec-causalcriteria" id="toc-sec-causalcriteria" class="nav-link" data-scroll-target="#sec-causalcriteria"><span class="header-section-number">9.1.1</span> Criteria for a causal relation</a></li>
  <li><a href="#sec-indirecteffect" id="toc-sec-indirecteffect" class="nav-link" data-scroll-target="#sec-indirecteffect"><span class="header-section-number">9.1.2</span> Mediation as indirect effect</a></li>
  <li><a href="#causal-process" id="toc-causal-process" class="nav-link" data-scroll-target="#causal-process"><span class="header-section-number">9.1.3</span> Causal process</a></li>
  </ul></li>
  <li><a href="#path-model-with-regression-analysis" id="toc-path-model-with-regression-analysis" class="nav-link" data-scroll-target="#path-model-with-regression-analysis"><span class="header-section-number">9.2</span> Path Model with Regression Analysis</a>
  <ul class="collapse">
  <li><a href="#requirements" id="toc-requirements" class="nav-link" data-scroll-target="#requirements"><span class="header-section-number">9.2.1</span> Requirements</a></li>
  <li><a href="#sec-size-indirect-effects" id="toc-sec-size-indirect-effects" class="nav-link" data-scroll-target="#sec-size-indirect-effects"><span class="header-section-number">9.2.2</span> Size of indirect effects</a></li>
  <li><a href="#direction-of-indirect-effects" id="toc-direction-of-indirect-effects" class="nav-link" data-scroll-target="#direction-of-indirect-effects"><span class="header-section-number">9.2.3</span> Direction of indirect effects</a></li>
  <li><a href="#sec-partialserialmediation" id="toc-sec-partialserialmediation" class="nav-link" data-scroll-target="#sec-partialserialmediation"><span class="header-section-number">9.2.4</span> Parallel and serial mediation</a></li>
  <li><a href="#sec-partialfullmediation" id="toc-sec-partialfullmediation" class="nav-link" data-scroll-target="#sec-partialfullmediation"><span class="header-section-number">9.2.5</span> Partial and full mediation</a></li>
  <li><a href="#significance-of-indirect-effects" id="toc-significance-of-indirect-effects" class="nav-link" data-scroll-target="#significance-of-indirect-effects"><span class="header-section-number">9.2.6</span> Significance of indirect effects</a></li>
  </ul></li>
  <li><a href="#sec-mediationcovariate" id="toc-sec-mediationcovariate" class="nav-link" data-scroll-target="#sec-mediationcovariate"><span class="header-section-number">9.3</span> Controlling for Covariates</a></li>
  <li><a href="#reporting-mediation-results" id="toc-reporting-mediation-results" class="nav-link" data-scroll-target="#reporting-mediation-results"><span class="header-section-number">9.4</span> Reporting Mediation Results</a></li>
  <li><a href="#sec-SPSSPROCESS" id="toc-sec-SPSSPROCESS" class="nav-link" data-scroll-target="#sec-SPSSPROCESS"><span class="header-section-number">9.5</span> Mediation with SPSS and PROCESS</a>
  <ul class="collapse">
  <li><a href="#instructions" id="toc-instructions" class="nav-link" data-scroll-target="#instructions"><span class="header-section-number">9.5.1</span> Instructions</a></li>
  </ul></li>
  <li><a href="#criticisms-of-mediation" id="toc-criticisms-of-mediation" class="nav-link" data-scroll-target="#criticisms-of-mediation"><span class="header-section-number">9.6</span> Criticisms of Mediation</a>
  <ul class="collapse">
  <li><a href="#causal-order-assumed" id="toc-causal-order-assumed" class="nav-link" data-scroll-target="#causal-order-assumed"><span class="header-section-number">9.6.1</span> Causal order assumed</a></li>
  <li><a href="#time-order" id="toc-time-order" class="nav-link" data-scroll-target="#time-order"><span class="header-section-number">9.6.2</span> Time order</a></li>
  <li><a href="#causality-or-underlying-construct" id="toc-causality-or-underlying-construct" class="nav-link" data-scroll-target="#causality-or-underlying-construct"><span class="header-section-number">9.6.3</span> Causality or underlying construct?</a></li>
  <li><a href="#every-effect-in-a-path-model-can-be-confounded" id="toc-every-effect-in-a-path-model-can-be-confounded" class="nav-link" data-scroll-target="#every-effect-in-a-path-model-can-be-confounded"><span class="header-section-number">9.6.4</span> Every effect in a path model can be confounded</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations"><span class="header-section-number">9.6.5</span> Recommendations</a></li>
  </ul></li>
  <li><a href="#combining-mediation-and-moderation" id="toc-combining-mediation-and-moderation" class="nav-link" data-scroll-target="#combining-mediation-and-moderation"><span class="header-section-number">9.7</span> Combining Mediation and Moderation</a></li>
  <li><a href="#take-home-points" id="toc-take-home-points" class="nav-link" data-scroll-target="#take-home-points"><span class="header-section-number">9.8</span> Take-Home Points</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ShKlinkenberg/Statistical-Inference/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/ShKlinkenberg/Statistical-Inference/blob/main/11-mediation.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/ShKlinkenberg/Statistical-Inference/edit/main/11-mediation.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-mediation" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Mediation with Regression Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>Key concepts: causality, causal and time order, common cause, direct, indirect, and total effects, causal model, path diagram and path model, parallel and serial mediation, partial mediation, covariate, controlling mediator values.</p>
</blockquote>
<p>Watch this micro lecture on mediation for an overview of the chapter (<a href="#vid-intro-mediation" class="quarto-xref">Video&nbsp;<span>9.1</span></a>).</p>
<div id="vid-intro-mediation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-vid figure">
<div aria-describedby="vid-intro-mediation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-video"><iframe data-external="1" src="https://www.youtube.com/embed/_cKP8d3ROtM" width="100%" height="360" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-vid" id="vid-intro-mediation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Video&nbsp;9.1: Introduction to mediation.
</figcaption>
</figure>
</div>
<section id="summary" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="summary">Summary</h3>
<div class="callout callout-style-simple callout-important">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Can I add a causal order to the predictors in my regression models?</p>
</div>
</div>
</div>
<p>If we add a causal order among the predictors of our regression model, we obtain a causal model or path model. The causal model includes an indirect effect: The first predictor affects the scores on the second predictor, which affects the scores on the dependent variable that we usually call the outcome variable. For example, age affects news site use, which affects newspaper reading time. In this path model, the second predictor (news site use) mediates the effect of the first predictor on the outcome variable. The second predictor is called a mediator.</p>
<p>We can estimate a path model as a series of regression models. The size of an indirect effect equals the product of the direct effects that constitute the indirect effect. With additional software, we can estimate the confidence interval of an indirect effect.</p>
<p>Mediation models help us to think about the different ways in which a variable may cause another variable. But we must realize that the causal order underlying the model is an assumption that we make. A regression model shows the predictive effects, which do not have to be causal. We cannot prove that the predictive effects are causal. We can only think of arguments that make a causal interpretation of a predictive effect plausible.</p>
<section id="essential-analytics" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="essential-analytics">Essential Analytics</h4>
<p>We can analyze a mediation model with a series of regression analyses in SPSS (the <em>Linear</em> option in the <em>Regression</em> submenu). We need one regression model for each variable that is predicted by one or more other variables in the model. The predicted variable is the dependent variable and as independent variables we use all variables that we think are causally prior to the dependent variable.</p>
<p>As an alternative, we may use the PROCESS macro for SPSS. The macro requires that we distinguish between parallel mediation (each indirect effect has just one mediator) and serial mediation (at least one indirect effect includes two or more mediators). PROCESS gives us the size and bootstrapped confidence intervals for all indirect effects of the selected predictor via mediators on the final outcome variable.</p>
<div id="fig-mediationtable" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediationtable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/S11_AE1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:75.0%" data-fig-pos="H"></p>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediationtable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: PROCESS output with estimated indirect and total effects of age on average newspaper reading time.
</figcaption>
</figure>
</div>
<p><a href="#fig-mediationtable" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> shows the results of a model in which political interest and news site use mediate the effect of age on newspaper reading time. Apart from a direct effect (<em>b</em> = 4.55, 95%CI[3.62, 5.47], red box in <a href="#fig-mediationtable" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>), three indirect effects have been estimated. Clearly the strongest indirect effect of age is the effect mediated by news site use (<a href="#fig-mediationtable" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>, green boxes). An additional unit of age increases predicted newspaper reading time by 1.44. The 95% confidence interval (95%CI[0.64, 2.24], bootstrapped) does not include zero, so this indirect effect is statistically significant at the .05 significance level.</p>
</section>
</section>
<section id="mediation-as-causal-process" class="level2 page-columns page-full" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="mediation-as-causal-process"><span class="header-section-number">9.1</span> Mediation as Causal Process</h2>
<div id="fig-mediation-commoncause" class="column-page-inset-right quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediation-commoncause-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<iframe src="https://sharon-klinkenberg.shinyapps.io/mediation-commoncause/" width="100%" height="325px" style="border:none;">
</iframe>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediation-commoncause-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: How does a common cause affect regression coefficients? The values in this path diagram represent standardized regression coefficients.
</figcaption>
</figure>
</div>
<section id="sec-causalcriteria" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="sec-causalcriteria"><span class="header-section-number">9.1.1</span> Criteria for a causal relation</h3>
<p>Researchers are usually interested in causal effects, so let us theorize a causal order between age and reading newspapers. From previous research and personal experience, we strongly suspect that older people spend more time on reading newspapers than young people. In statistical language, we expect a positive correlation between age and newspaper reading time. Can age be a cause of current newspaper reading?</p>
<p>Correlation is the first criterion. A causal relation implies correlation or another type of statistical association. If newspaper reading is not correlated with age, it is hard to imagine that age affects newspaper reading. But correlation does not imply causation, as the saying goes. Correlated variables do not have to be causally related. We need additional arguments to add plausibility to a causal relation.</p>
<p>The second criterion is the time order between cause and consequence. A cause must appear before the consequence. In our example, a person’s age must be fixed before she displays the behaviour that we want to explain, namely reading newspapers. The time order is very plausible here because age stands for the moment a person was born, which must be prior in time to reading newspapers. If there is a causal relation between age and reading newspapers, age must be the cause and newspaper reading the consequence.</p>
<p>A third criterion for causality is that the correlation is not spurious. In <a href="10-confounding.html#sec-spuriousness" class="quarto-xref"><span>Section 8.3.2</span></a>, we have encountered a spurious effect as an effect that incorrectly includes the effect of a confounder (reinforcer).</p>
<p>In the context of causality, spuriousness is linked to a confounder that is a <em>common cause</em> to both the assumed cause (predictor) and consequence (dependent variable). Age, for instance, can be a common cause both to having (grand)children and reading newspapers. Older people tend to have more (grand)children and they read more newspapers. If we do not control for age in a regression model predicting newspaper reading time from the number of (grand)children a person has, we may find a positive effect.</p>
<p>This effect is probably not causal: We do not spend more time reading newspapers because we have more (grand)children. Unless we use newspaper reading to ignore our children and grandchildren when they are around. Most if not all of the effect of (grand)children on newspaper reading is spurious because it results from a common cause, namely age or the habits and opportunities represented by age.</p>
<p>To interpret an effect that we find as causal, then, we must ensure that there are no confounding variables that are common causes to both our predictors and dependent variable. Including them as controls in the regression model is a way to solve the problem (<a href="10-confounding.html" class="quarto-xref"><span>Chapter 8</span></a>). With non-experimental data, for example data on newspaper reading habits gathered in a survey, we cannot be sure that we have included all common causes in our model. In this situation, we should always keep in mind that the effects that we find may be caused by variables not included in our regression model. In an experiment, however, we can use experimental randomization to minimize the chance of having any confounders at all (<a href="10-confounding.html#sec-randomization" class="quarto-xref"><span>Section 8.2.2</span></a>).</p>
</section>
<section id="sec-indirecteffect" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="sec-indirecteffect"><span class="header-section-number">9.1.2</span> Mediation as indirect effect</h3>
<p>A common cause does not have to remove the entire effect between a predictor and dependent variable. Even if part of newspaper reading is caused by age, another part can be caused by a variable related to age, for example, interest in politics. During their lifetime, people may gain more experience with politics and, for that reason, become more interested in reading about politics. This may cause them to invest more time in reading newspapers for collecting information.</p>
<p>Not all people become more interested in politics as they grow older and their interest in politics does not have to increase regularly during all of their lifetime. The relation between age and interest in politics, therefore, will not be perfect. This allows us to technically distinguish between the effect of age and the effect of interest in politics.</p>
<p>If we include both age and interest in politics as predictors in a regression model for newspaper reading time, the partial effect (<a href="10-confounding.html#sec-partialeffect" class="quarto-xref"><span>Section 8.1.1</span></a>) of interest in politics is corrected for the spurious correlation between interest in politics and newspaper reading caused by age as their common cause. The partial effect of political interest can be interpreted as causal if current interest in politics was attained before the newspaper readings that we measure (very plausible) and age is the only common cause of interest in politics and newspaper reading (highly questionable).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-causaldiagram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causaldiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-causaldiagram-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causaldiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Causal diagram for the effects of age and interest in politics on newspaper reading time.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now let us draw the <em>causal diagram</em> for this simple example (<a href="#fig-causaldiagram" class="quarto-xref">Figure&nbsp;<span>9.3</span></a>). A causal diagram contains the names of the variables with arrows pointing from causes to consequences. The causal order of variables is represented from left to right. In <a href="#fig-causaldiagram" class="quarto-xref">Figure&nbsp;<span>9.3</span></a>, the very first cause (age) is at the left, the final consequence (newspaper reading time) is at the right, and interest in politics is placed in the middle. In this layout, the arrows always point to the right.</p>
<p>In the causal order that we theorize, age is causally prior (antecedent) to interest in politics, which is causally prior to current newspaper reading time. We have an <em>indirect effect</em> of age on newspaper reading by way of interest in politics. When adults grow older, they tend to be more interested in politics and because of this, they tend to spend more time on reading newspapers. We say that interest in politics <em>mediates</em> the effect of age on newspaper reading time. Interest in politics is a <em>mediator</em>, an <em>intermediary variable</em>, or an <em>intervening variable</em> in this causal diagram.</p>
<p>A causal diagram like <a href="#fig-causaldiagram" class="quarto-xref">Figure&nbsp;<span>9.3</span></a> is also called a <em>path diagram</em>. Each indirect effect is a sequence of direct effects. Each direct effect is a “step” from one variable to another variable, represented by an arrow. An indirect effect, then, can be regarded as a <em>path</em> that we can follow to “travel” from one variable to another variable.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-causaldiagram2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causaldiagram2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-causaldiagram2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causaldiagram2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: Causal diagram for the effect of age on newspaper reading time mediated by interest in politics and news site use.
</figcaption>
</figure>
</div>
</div>
</div>
<p>An indirect effect may contain more than one step or mediator. If we include news site use in the model (<a href="#fig-causaldiagram2" class="quarto-xref">Figure&nbsp;<span>9.4</span></a>), we would have an indirect effect of age via interest in politics via news site use on newspaper reading time.</p>
<div class="callout callout-style-simple callout-important">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<ul>
<li>Mediation: A causal relationship between a predictor, one or more mediators, and an outcome variable.</li>
<li>Indirect effect: An effect in which three (or more) variables affect each other in a causal order: the predictor affects the mediator, the mediator affects another mediator or the outcome variable.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="causal-process" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="causal-process"><span class="header-section-number">9.1.3</span> Causal process</h3>
<p>In our example (<a href="#fig-causaldiagram2" class="quarto-xref">Figure&nbsp;<span>9.4</span></a>), age has a direct effect on newspaper reading time. What does the direct effect mean? If we start thinking about why older people spend more time on reading newspapers, we soon realize that this is probably not some biological process. It is hard to believe that an ageing human body requires more newspaper reading time. The effect is more likely to be social.</p>
<p>In the middle of the 20th century, newspapers were among the most important sources of information. A person who was born and grew up in that period is accustomed to using newspapers as main information source. For later generations, however, news sites on the internet have become important sources of information. Newspapers being less important to them, they are less oriented and accustomed to reading newspapers.</p>
<p>This line of reasoning shows us two things. First, we discover that our common cause may actually represent different things. Age, for instance, refers to life experience in its effect on interest in politics. In contrast, it relates to the period of coming of age in its direct effect on newspaper reading time.</p>
<p>Our second discovery is that we usually look for mediators if we want to understand a direct effect. Date of birth affects exposure to people using newspapers as information sources, which affects the habit of reading newspapers, which finally affects the time spent on reading newspapers later on. Exposure and habit are mediators here. A direct effect of age on newspaper reading represents a causal process that may contain many intermediary steps. Adding mediators to our model is a way of getting more insight in the causal process.</p>
</section>
</section>
<section id="path-model-with-regression-analysis" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="path-model-with-regression-analysis"><span class="header-section-number">9.2</span> Path Model with Regression Analysis</h2>
<p>Mediation or, more generally, path models can be estimated with a series of regression models. Every variable in the path diagram with at least one predictor (or incoming arrow) is a dependent variable, so for each of them, we estimate a regression model. The regression model contains all variables as predictors that may cause changes in the dependent variable. In other words, all variables that are causally prior to the outcome are used as predictors. In a well-designed causal diagram, all variables to the left of the outcome are causally prior to it.</p>
<div class="cell">
<div id="fig-mediation-regression" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediation-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="htmlwidget-89c51dc64933e09e6389" style="width:100%;height:480px;" class="visNetwork html-widget"></div>
<script type="application/json" data-for="htmlwidget-89c51dc64933e09e6389">{"x":{"nodes":{"id":[1,2,3],"x":[0,550,1000],"y":[500,0,500],"label":["Age (/10)","Pol. Interest","Newspaper \n Reading Time"],"shape":["box","box","box"],"font.size":[42,42,42],"shadow":["FALSE","FALSE","FALSE"],"physics":[false,false,false],"borderWidth":[1,1,1],"color.background":["white","white","white"],"color.border":["black","black","black"]},"edges":{"from":[1,1,2],"to":[2,3,3],"label":["0.1 \n [0; 0.19]","5.99 \n [5.64; 6.35]","0.32 \n [-0.09; 0.74]"]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"dot"},"manipulation":{"enabled":false},"edges":{"arrows":"to","font":{"size":30}},"interaction":{"dragNodes":true,"multiselect":true,"zoomSpeed":1}},"groups":null,"width":"100%","height":null,"idselection":{"enabled":false,"style":"width: 150px; height: 26px","useLabels":true,"main":"Select by id"},"byselection":{"enabled":false,"style":"width: 150px; height: 26px","multiple":false,"hideColor":"rgba(200,200,200,0.5)","highlight":false},"main":null,"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","highlight":{"enabled":true,"hoverNearest":false,"degree":{"from":1,"to":0},"algorithm":"hierarchical","hideColor":"rgba(200,200,200,0.5)","labelOnly":true},"collapse":{"enabled":false,"fit":false,"resetHighlight":true,"clusterOptions":null,"keepCoord":true,"labelSuffix":"(cluster)"},"tooltipStay":300,"tooltipStyle":"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);"},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediation-regression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: Path diagram with unstandardized effect sizes and their 95% confidence intervals.
</figcaption>
</figure>
</div>
</div>
<p>In the path diagram displayed in <a href="#fig-mediation-regression" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>, we would regress newspaper reading time, the final dependent variable, on age and political interest. As a next step, we would predict political interest as outcome from age.</p>
<section id="requirements" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="requirements"><span class="header-section-number">9.2.1</span> Requirements</h3>
<p>We can estimate mediation and path models with regression analysis if we meet the following requirements:</p>
<ol type="1">
<li><p>Each variable used as a dependent variable is numeric. This is a general requirement of a linear regression model. In a path diagram, it means that all mediators and dependent variables must be numeric.</p>
<p>For detail lovers: Variables with only incoming arrows may be dichotomous but that requires logistic regression, which we do not discuss.</p></li>
<li><p>Each variable used only as a predictor must be a numeric or dichotomous (dummy) variable. Again, this is a general requirement of regression models.</p></li>
<li><p>There are no causal feedback loops. Causality must work in one direction. It must be impossible to travel from a variable back to it while following the direction of the arrows. Note that it can be difficult to assign a causal order. For example, does political interest cause (low) political cynicism or the other way around? Or are they not causally related at all?</p></li>
<li><p>All regression models meet the assumptions for regression analysis. Check if the residuals are normally distributed, centered around zero for all levels of the predicted outcome scores, and that scores are predicted equally well at all outcome levels (see <a href="08-moderation-categorical.html#sec-regr-inference" class="quarto-xref"><span>Section 6.1.4</span></a>).</p></li>
</ol>
</section>
<section id="sec-size-indirect-effects" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="sec-size-indirect-effects"><span class="header-section-number">9.2.2</span> Size of indirect effects</h3>
<p>The regression results tell us the sizes and statistical significance of all direct effects on the dependent variable. Both unstandardized and standardized regression coefficients can be used to interpret effects in the usual way. But how do we obtain the size, confidence interval, and statistical significance of indirect effects?</p>
<p>The size of an indirect effect is calculated in exactly the same way as the size of indirect correlations (<a href="10-confounding.html#sec-indirectcorrelation" class="quarto-xref"><span>Section 8.2</span></a>): Just multiply the size of direct effects. This can be done with either the standardized regression coefficients or the unstandardized regression coefficients.</p>
<div class="cell">
<div id="fig-pathdiagram-unstandardized" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pathdiagram-unstandardized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="htmlwidget-2911581868155f87d6f3" style="width:100%;height:480px;" class="visNetwork html-widget"></div>
<script type="application/json" data-for="htmlwidget-2911581868155f87d6f3">{"x":{"nodes":{"id":[1,2,3],"x":[0,550,1000],"y":[500,0,500],"label":["Age (/10)","Pol. Interest","Newspaper \n Reading Time"],"shape":["box","box","box"],"font.size":[42,42,42],"shadow":["FALSE","FALSE","FALSE"],"physics":[false,false,false],"borderWidth":[1,1,1],"color.background":["white","white","white"],"color.border":["black","black","black"]},"edges":{"from":[1,1,2],"to":[2,3,3],"label":["0.1 \n [0; 0.19]","5.99 \n [5.64; 6.35]","0.32 \n [-0.09; 0.74]"]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"dot"},"manipulation":{"enabled":false},"edges":{"arrows":"to","font":{"size":30}},"interaction":{"dragNodes":true,"zoomSpeed":1}},"groups":null,"width":"100%","height":null,"idselection":{"enabled":false},"byselection":{"enabled":false},"main":null,"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","tooltipStay":300,"tooltipStyle":"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);"},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pathdiagram-unstandardized-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: Path diagram with unstandardized effect sizes and their 95% confidence intervals.
</figcaption>
</figure>
</div>
</div>
<p>It may sound weird that we can multiply the unstandardized regression coefficients but it really works. In <a href="#fig-pathdiagram-unstandardized" class="quarto-xref">Figure&nbsp;<span>9.6</span></a>, for instance, the unstandardized partial effect of age (measured in tens of years) on interest in politics is 0.1. This means that an additional 10 years of life predict an average increase in interest in politics of 0.1.</p>
<p>In its turn, interest in politics has an unstandardized effect of 0.32 on reading time (in minutes). An additional unit of interest in politics predicts an average increase in reading time of 0.32 minutes.</p>
<p>Ten additional years of life only predict an increase of 0.1 in political interest, not a full unit increase. The predicted increase of 0.1 in political interest predicts 0.1 * 0.32 = 0.03 minutes of additional newspaper reading time. As a result, an additional ten years of life predict 0.1 * 0.32 = 0.03 minutes of additional newspaper reading time as an indirect effect via political interest.</p>
<p>Note that the indirect effect is interpreted in terms of the measurement units of the initial predictor (age in tens of years) and the final outcome (reading time in minutes): A difference in (tens of) years predicts a difference in reading time in minutes. As a consequence, we can directly compare unstandardized indirect effect sizes of different paths between the same predictor and outcome, as we will see in <a href="#sec-partialfullmediation" class="quarto-xref"><span>Section 9.2.5</span></a>.</p>
</section>
<section id="direction-of-indirect-effects" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="direction-of-indirect-effects"><span class="header-section-number">9.2.3</span> Direction of indirect effects</h3>
<p>Multiplication of direct effects assigns the right direction (positive or negative) to indirect effects. In the example above, age has a positive effect on interest in politics, which has a positive effect on newspaper reading time. If age goes up, interest in politics goes up and if interest in politics goes up, reading time increases. Thus, higher age is indirectly associated with more reading time through interest in politics: Plus times plus yields a plus.</p>
</section>
<section id="sec-partialserialmediation" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="sec-partialserialmediation"><span class="header-section-number">9.2.4</span> Parallel and serial mediation</h3>
<p>If each indirect effect in a path model contains at most one mediator, we have <em>single mediation</em> or <em>parallel mediation</em>. <a href="#fig-mediationparallel" class="quarto-xref">Figure&nbsp;<span>9.7</span></a> illustrates single and parallel mediation.</p>
<div id="fig-mediationparallel" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediationparallel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mediationparallel" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mediationparallel-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mediationparallel-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-mediationparallel-1.png" class="img-fluid figure-img" data-ref-parent="fig-mediationparallel" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mediationparallel-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Single mediation.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-mediationparallel" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-mediationparallel-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-mediationparallel-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-mediationparallel-2.png" class="img-fluid figure-img" data-ref-parent="fig-mediationparallel" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-mediationparallel-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Parallel mediation.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediationparallel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7: Causal diagrams for:.
</figcaption>
</figure>
</div>
<p>If at least one of the indirect effects in a path model contains two or more mediators, we are dealing with <em>serial mediation</em>. <a href="#fig-mediationserial" class="quarto-xref">Figure&nbsp;<span>9.8</span></a> illustrates serial mediation. It contains an indirect effect from age on reading time with two mediators: Age &gt; Political Interest &gt; News Site Use &gt; Reading Time. The distinction between parallel and serial mediation is relevant to the software (PROCESS) that we will use to estimate indirect and total effects (<a href="#sec-SPSSPROCESS" class="quarto-xref"><span>Section 9.5</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mediationserial" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mediationserial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-mediationserial-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mediationserial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.8: Causal diagram for serial mediation.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-partialfullmediation" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="sec-partialfullmediation"><span class="header-section-number">9.2.5</span> Partial and full mediation</h3>
<p>The unstandardized direct effect and indirect effects between a predictor and outcome can be compared directly because they are all expressed in the same measurement units, namely the predicted change in the dependent variable (reading time in minutes) for a difference of one unit in the predictor (ten additional years of life) (<a href="#sec-size-indirect-effects" class="quarto-xref"><span>Section 9.2.2</span></a>). Because of this, we can sum the unstandardized direct and indirect effects to obtain the total unstandardized effect.</p>
<p>With this in mind, we see that the relation between age and newspaper reading time is dominated by the positive direct effect (<em>b</em> = 5.99) and the positive indirect effect via news site use (<em>b</em> = 0.03). The remaining indirect effects are relatively small as indirect effects usually are.</p>
<p>Summing all effects, we obtain a <em>total effect</em> of age on newspaper reading time around 6 (<em>b</em> = 6.03). A person who is ten years older but in other respects the same as another person, is predicted to spend on average 6 additional minutes on reading newspapers per day.</p>
<p>If the direct effect of a predictor on the outcome is zero in a model with mediators, the predictor’s effect is <em>fully mediated</em>. This clearly is not the case in our example: There still is a substantial direct effect of age on newspaper reading time. This is what we usually encounter; it is called <em>partial mediation</em>.</p>
<p>Sometimes, researchers decide that an effect is fully mediated if the direct effect is no longer statistically significant once a mediator is added to the model. This strategy is contestable because a statistically non-significant direct effect does not mean that the effect is absent (zero) in the population. It can be absent but it is much more likely to be present but just too small to be picked up by our significance test (see <a href="04-hypothesis.html#sec-true-effect-size" class="quarto-xref"><span>Section 4.2.7</span></a>).</p>
<p>The distinction between full and partial mediation is a little bit problematic. From a substantive point of view, we may argue that direct effects are probably always mediated. As we have seen in <a href="#sec-indirecteffect" class="quarto-xref"><span>Section 9.1.2</span></a>, a direct effect usually summarizes a causal process that consists of intermediary steps, which is mediation. We may wonder whether it makes theoretical sense to talk about unmediated effects. Do we really believe that age can directly affect newspaper reading time?</p>
<p>If the variables that we entered in the model as mediators do not create any indirect effects, the direct effect is equal to the total effect. We may conclude that the direct effect is not mediated by the mediators that are included in the model. For example, if education, political interest, and news site use do not create indirect effects from age on newspaper reading time (<a href="#fig-pathdiagram-unstandardized" class="quarto-xref">Figure&nbsp;<span>9.6</span></a>), we only have the direct effect of age on reading time in our model. However, this effect is very likely to be mediated by other variables that we did not include in the model. We should not conclude that the effect is unmediated because we have not found mediation yet.</p>
</section>
<section id="significance-of-indirect-effects" class="level3" data-number="9.2.6">
<h3 data-number="9.2.6" class="anchored" data-anchor-id="significance-of-indirect-effects"><span class="header-section-number">9.2.6</span> Significance of indirect effects</h3>
<p>SPSS does not calculate the size of indirect effects for us or their confidence intervals and <em>p</em> values. It is easy to calculate the sizes of indirect effects, as we have seen in a preceding section: just take the product of direct effects.</p>
<p>In contrast, it is not possible to calculate the confidence interval or <em>p</em> value of an indirect effect in a reliable way from the confidence intervals or <em>p</em> values of the direct effects <span class="citation" data-cites="RefWorks:3873">(see <a href="14-references.html#ref-RefWorks:3873" role="doc-biblioref">Hayes 2013</a>: Section 4.4 for a detailed and critical discussion of approaches that try to calculate the <em>p</em> value of an indirect effect from <em>p</em> values of direct effects)</span>.</p>
<p>We use bootstrapping to create the sampling distribution of the size of an indirect effect. We have learned the principles and limitations of bootstrapping in <a href="02-probability.html#sec-boot-approx" class="quarto-xref"><span>Section 2.5</span></a>, so we do not have to go into details here. Suffice it to repeat that our original sample must not be too small and it must be quite representative of the population if we apply bootstrapping.</p>
<div class="cell">
<div id="tbl-indirect-sim" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-indirect-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1
</figcaption>
<div aria-describedby="tbl-indirect-sim-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Effect
</th>
<th style="text-align:right;">
Boot SE
</th>
<th style="text-align:right;">
BootLLCI
</th>
<th style="text-align:right;">
BootULCI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Total indirect effect
</td>
<td style="text-align:right;">
1.47
</td>
<td style="text-align:right;">
.42
</td>
<td style="text-align:right;">
.62
</td>
<td style="text-align:right;">
2.25
</td>
</tr>
<tr>
<td style="text-align:left;">
Age - Pol. Interest - Reading Time
</td>
<td style="text-align:right;">
.05
</td>
<td style="text-align:right;">
.03
</td>
<td style="text-align:right;">
.01
</td>
<td style="text-align:right;">
.14
</td>
</tr>
<tr>
<td style="text-align:left;">
Age - Pol. Interest - News Site Use - Reading Time
</td>
<td style="text-align:right;">
-.02
</td>
<td style="text-align:right;">
.01
</td>
<td style="text-align:right;">
-.05
</td>
<td style="text-align:right;">
.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Age - News Site Use - Reading Time
</td>
<td style="text-align:right;">
1.44
</td>
<td style="text-align:right;">
.42
</td>
<td style="text-align:right;">
.60
</td>
<td style="text-align:right;">
2.23
</td>
</tr>
</tbody>
</table>
<p>Bootstrap results for unstandardized indirect effects in a model with two mediators. Effect size, standard error, lower and upper levels of the 95% confidence interval.</p>
</div>
</div>
</figure>
</div>
</div>
<p>The confidence interval of an indirect effect can be calculated from its bootstrapped sampling distribution. <a href="#tbl-indirect-sim" class="quarto-xref">Table&nbsp;<span>9.1</span></a> shows bootstrap results for the indirect effects in a model with age as predictor, newspaper reading time as dependent variable, and interest in politics and news site use as mediators.</p>
<p>In total, there is a substantial indirect effect of age on newspaper reading time in this model. We are confident that this effect is positive [<em>b</em> = 1.47, 95% CI [0.62, 2.25] (bootstrapped)]. It is easy to see that the indirect effect of age via news site use on reading time is by far the most important indirect effect [<em>b</em> = 1.44, 95% CI [0.60, 2.23] (bootstrapped)]. On its own, it is responsible for almost the entire total indirect effect.</p>
<p>It may happen that an indirect effect is not statistically significant (the confidence interval includes zero) whereas all direct effects that constitute the indirect effect are statistically significant. In <a href="#fig-causaldiagram3" class="quarto-xref">Figure&nbsp;<span>9.9</span></a>, for example, both the effect of age on political interest (<em>b</em> = 0.30, 95% CI [0.22, 0.38]) and the effect of political interest on reading time (<em>b</em> = 0.20, 95% CI [0.12, 0.28]) are statistically significant at the .05 level. The indirect effect of age via political interest on reading time, however, is not statistically significant at this level [<em>b</em> = 0.30 * 0.20 = 0.06, 95% CI [-0.02, 0.14], (bootstrapped)].</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-causaldiagram3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causaldiagram3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-causaldiagram3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causaldiagram3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.9: Causal diagram for the effects of age and interest in politics on newspaper reading time: unstandardized estimates with 95% confidence intervals.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This sounds like a paradox but it should not upset you. The unstandardized indirect effect tends to be weaker than the direct effects, that is, closer to zero. With a weaker effect, it is more difficult to reject the null hypothesis that the effect is zero in the population. We need a larger sample to reject null hypotheses for smaller effects (see <a href="04-hypothesis.html#sec-power" class="quarto-xref"><span>Section 4.2.3</span></a> on power). In this case, report that all direct effects that create the indirect effect are statistically significant, so non-significance is likely to arise from low test power rather than from absence of an indirect effect in the population.</p>
</section>
</section>
<section id="sec-mediationcovariate" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-mediationcovariate"><span class="header-section-number">9.3</span> Controlling for Covariates</h2>
<p>We usually have theoretical reasons to expect that a variable mediates an effect, for example, that political interest mediates the effect of age on newspaper reading time. At the same time, we know that our dependent variable and perhaps our mediator may depend on other variables. Newspaper reading time, for instance, may also depend on education. In this situation, we would use the other variables as covariates (or control variables) for which we want to control statistically.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-causaldiagram4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causaldiagram4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-causaldiagram4-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causaldiagram4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.10: Causal diagram for interest in politics as mediator between age and newspaper reading time with education as covariate.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-causaldiagram4" class="quarto-xref">Figure&nbsp;<span>9.10</span></a> presents a model in which education is used as a covariate in a model with political interest mediating the effect of age on newspaper reading time. Education is probably causally prior to both political interest and newspaper reading time, so it is allowed to have an effect on both variables. In this way, we control for education and remove spurious correlation between political interest and newspaper reading time due to education as a common cause.</p>
<p>If education predicts political interest and political interest predicts newspaper reading time as in <a href="#fig-causaldiagram4" class="quarto-xref">Figure&nbsp;<span>9.10</span></a>, political interest mediates the effect of education on newspaper reading time. We are, however, not interested in mediation in the case of a covariate, so we do not estimate or report the indirect effects of education on newspaper reading time. In the context of a mediation model, a <em>covariate</em> is a predictor for which we do not investigate if its effect is mediated.</p>
<p>Note that covariates should only be allowed to have an effect on variables that can be caused by the covariate. We should not include effects of a covariate on a variable that is causally prior to it. If a covariate is a consequence rather than a cause of a mediator, it had better be used as another mediator in the model. If, for instance, political cynicism may affect newspaper reading time but it is a consequence of political interest, it should be included as a second (serial) mediator instead of as a covariate.</p>
</section>
<section id="reporting-mediation-results" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="reporting-mediation-results"><span class="header-section-number">9.4</span> Reporting Mediation Results</h2>
<p>We analyse a path model as a series of regression models, so the general rules for reporting mediation are the same as for reporting regression analyses (see <a href="09-moderation-continuous.html#sec-reportmoderation" class="quarto-xref"><span>Section 7.2</span></a>). If you summarize results in a table, make sure that the table includes:</p>
<ol type="1">
<li>The unstandardized regression coefficients for all direct and indirect effects tested in the regression models.</li>
<li>The confidence intervals and significance levels of the unstandardized effects.</li>
<li>The <em>F</em> test and measure of model fit (<span class="math inline">\(R^2\)</span>) for each regression model.</li>
</ol>
<div class="cell">
<div id="tbl-mediation-table" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-mediation-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.2
</figcaption>
<div aria-describedby="tbl-mediation-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table style="NAborder-bottom: 0; font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;" class="table">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
B
</th>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
95% CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<strong>Outcome: News Site Use</strong>
</td>
<td style="text-align:right;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
constant
</td>
<td style="text-align:right;">
6.62
</td>
<td style="text-align:left;">
***
</td>
<td style="text-align:center;">
[5.92; 7.31]
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
-0.93
</td>
<td style="text-align:left;">
***
</td>
<td style="text-align:center;">
[-0.97; -0.88]
</td>
</tr>
<tr>
<td style="text-align:left;">
education
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:left;">
*
</td>
<td style="text-align:center;">
[0.01; 0.11]
</td>
</tr>
<tr>
<td style="text-align:left;">
pol.interest
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:left;">
***
</td>
<td style="text-align:center;">
[0.06; 0.17]
</td>
</tr>
<tr>
<td style="text-align:left;">
R<sup>2</sup>
</td>
<td style="text-align:right;">
0.86
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
F (3, 308)
</td>
<td style="text-align:right;">
617.40
</td>
<td style="text-align:left;">
***
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Outcome: Newspaper Reading Time</strong>
</td>
<td style="text-align:right;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
constant
</td>
<td style="text-align:right;">
13.59
</td>
<td style="text-align:left;">
**
</td>
<td style="text-align:center;">
[5.26; 21.93]
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
4.54
</td>
<td style="text-align:left;">
***
</td>
<td style="text-align:center;">
[3.62; 5.47]
</td>
</tr>
<tr>
<td style="text-align:left;">
education
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
[-0.34; 0.46]
</td>
</tr>
<tr>
<td style="text-align:left;">
pol.interest
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:left;">
*
</td>
<td style="text-align:center;">
[0.07; 0.96]
</td>
</tr>
<tr>
<td style="text-align:left;">
newssite
</td>
<td style="text-align:right;">
-1.55
</td>
<td style="text-align:left;">
**
</td>
<td style="text-align:center;">
[-2.47; -0.64]
</td>
</tr>
<tr>
<td style="text-align:left;">
R<sup>2</sup>
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
F (4, 307)
</td>
<td style="text-align:right;">
290.85
</td>
<td style="text-align:left;">
***
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
<strong>Indirect Effect</strong>
</td>
<td style="text-align:right;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Age &gt; News Site Use &gt; Reading Time
</td>
<td style="text-align:right;">
1.44
</td>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
[0.61; 2.17]
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<span style="font-style: italic;">Note.</span> <sup></sup> * <em>p</em> &lt; .05. ** <em>p</em> &lt; .01. *** <em>p</em> &lt; .001.
</td>
</tr>
</tfoot>
</table>
<p>Unstandardized effects in a model regressing newspaper reading time on age with one mediator (News Site Use) and two covariates (Education, Political Interest). Theoretical approximation for direct effects, bootstrap results for indirect effects, using 5,000 bootstraps.</p>
</div>
</div>
</figure>
</div>
</div>
<p>A path model may yield a lot of direct effects, so it is good practice to present results as a path diagram with the values of the standardized or unstandardized regression coefficients as labels to the arrows. A path model conveniently summarizes the results for the reader (<a href="#fig-results-pathdiagram" class="quarto-xref">Figure&nbsp;<span>9.11</span></a>). Remember that we don’t use standardized regression coefficients if the predictor or a covariate is dichotomous variable or a set of dummy variables (see <a href="08-moderation-categorical.html#sec-dichpredictor" class="quarto-xref"><span>Section 6.1.2</span></a>).</p>
<div class="cell">
<div id="fig-results-pathdiagram" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-results-pathdiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="htmlwidget-cc92330a37879456876e" style="width:100%;height:480px;" class="visNetwork html-widget"></div>
<script type="application/json" data-for="htmlwidget-cc92330a37879456876e">{"x":{"nodes":{"id":[1,2,3,4,5],"x":[0,100,300,360,1000],"y":[550,0,75,300,550],"label":["Age (/10)","Education","Pol. Interest","News Site Use","Newspaper \n Reading Time"],"shape":["box","box","box","box","box"],"font.size":[42,42,42,42,42],"shadow":["FALSE","FALSE","FALSE","FALSE","FALSE"],"physics":[false,false,false,false,false],"borderWidth":[1,1,1,1,1],"color.background":["white","white","white","white","white"],"color.border":["black","black","black","black","black"]},"edges":{"from":[1,2,3,1,2,3,4],"to":[4,4,4,5,5,5,5],"color.highlight":["#2B83BA","#2B83BA","#2B83BA","#2B83BA","#2B83BA","#2B83BA","#2B83BA"],"shadow":[false,false,false,false,false,false,false],"label":["-0.93","0.06","0.12","Direct: b = 4.54, 95% CI [3.62, 5.47]\nIndirect effect: b = 1.44, 95% CI [0.61, 2.17]","0.06","0.52","-1.55"],"font.color":["#D7191C","#2B83BA","#2B83BA","#2B83BA","#2B83BA","#2B83BA","#D7191C"],"font.size":[35,35,35,35,35,35,35]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"dot"},"manipulation":{"enabled":false},"edges":{"arrows":"to"},"interaction":{"dragNodes":true,"zoomSpeed":1}},"groups":null,"width":"100%","height":null,"idselection":{"enabled":false,"style":"width: 150px; height: 26px","useLabels":true,"main":"Select by id"},"byselection":{"enabled":false,"style":"width: 150px; height: 26px","multiple":false,"hideColor":"rgba(200,200,200,0.5)","highlight":false},"main":null,"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","highlight":{"enabled":true,"hoverNearest":false,"degree":{"from":1,"to":0},"algorithm":"hierarchical","hideColor":"rgba(200,200,200,0.5)","labelOnly":true},"collapse":{"enabled":false,"fit":false,"resetHighlight":true,"clusterOptions":null,"keepCoord":true,"labelSuffix":"(cluster)"},"tooltipStay":300,"tooltipStyle":"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);"},"evals":[],"jsHooks":[]}</script>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-results-pathdiagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.11: Unstandardized direct effects for a path model with one mediator and two covariates.
</figcaption>
</figure>
</div>
</div>
<p>If effect mediation is central to your report, focus your presentation and interpretation on the indirect effects and compare them to the direct effects. Report the size and confidence interval of each indirect effect. If possible, add both the direct and indirect effect to a diagram such as <a href="#fig-results-pathdiagram" class="quarto-xref">Figure&nbsp;<span>9.11</span></a>.</p>
<p>Interpret an unstandardized indirect effect just like any unstandardized regression effect, namely, as the predicted difference in the outcome for a one unit difference in the predictor. It is usually interesting to compare the sizes of the direct and indirect effects. Is the effect predominantly mediated in the model or is only a minor part of the effect mediated in the model?</p>
<p>Inform the reader that you bootstrapped the indirect effect and report the number of bootstrap samples and the method used for the confidence intervals (see <a href="#sec-SPSSPROCESS" class="quarto-xref"><span>Section 9.5</span></a>). For a more elaborate discussion of reporting mediation, see Hayes <span class="citation" data-cites="RefWorks:3873">(<a href="14-references.html#ref-RefWorks:3873" role="doc-biblioref">2013</a>: 198-202)</span>.</p>
</section>
<section id="sec-SPSSPROCESS" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-SPSSPROCESS"><span class="header-section-number">9.5</span> Mediation with SPSS and PROCESS</h2>
<section id="instructions" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="instructions"><span class="header-section-number">9.5.1</span> Instructions</h3>
<p>SPSS cannot apply statistical inference to indirect effects, so we use the PROCESS macro developed for this purpose <span class="citation" data-cites="RefWorks:3873">(<a href="14-references.html#ref-RefWorks:3873" role="doc-biblioref">Hayes 2013</a>)</span>. If correctly installed (see below), the macro can be used from within the SPSS Regression menu. Please note that you had better not paste the PROCESS commands to the SPSS syntax because it produces a lot of code that is difficult to understand. Instead, run the PROCESS command directly from the menu and manually add a comment to your SPSS syntax file reminding yourself of the model that you estimated with PROCESS.</p>
<p><a href="http://processmacro.org/download.html">Download the PROCESS macro</a> and <a href="http://www.processmacro.org/uploads/3/4/8/5/34858384/dialoginstall.pdf">install the SPSS custom dialog file</a>. Check the <a href="http://processmacro.org/faq.html">FAQ at the PROCESS website</a> if installation is not successful. If PROCESS is successfully installed, it can be found in the Analyze &gt; Regression menu.</p>
<hr>
<div id="vid-SPSSmediatpar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-vid figure">
<div aria-describedby="vid-SPSSmediatpar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-video"><iframe data-external="1" src="https://www.youtube.com/embed/YLxODUTflbQ" width="100%" height="315" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-vid" id="vid-SPSSmediatpar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Video&nbsp;9.2: Estimating a single or parallel mediation model with PROCESS.
</figcaption>
</figure>
</div>
<hr>
<div id="vid-SPSSmediatserial" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-vid figure">
<div aria-describedby="vid-SPSSmediatserial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-video"><iframe data-external="1" src="https://www.youtube.com/embed/VN_mgu5CQ4Y" width="100%" height="315" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-vid" id="vid-SPSSmediatserial-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Video&nbsp;9.3: Estimating a serial mediation model with PROCESS (Model 6).
</figcaption>
</figure>
</div>
<hr>
<div id="vid-SPSSmediatcov" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-vid figure">
<div aria-describedby="vid-SPSSmediatcov-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-video"><iframe data-external="1" src="https://www.youtube.com/embed/qK1KYgSwpss" width="100%" height="315" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-vid" id="vid-SPSSmediatcov-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Video&nbsp;9.4: Estimating a (single mediator) mediation model including covariates with PROCESS.
</figcaption>
</figure>
</div>
<hr>
<div id="vid-SPSSpath" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-vid figure">
<div aria-describedby="vid-SPSSpath-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-video"><iframe data-external="1" src="https://www.youtube.com/embed/olOEqeZE9WE" width="100%" height="315" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-vid" id="vid-SPSSpath-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Video&nbsp;9.5: Getting standardized direct effects and checking assumptions in SPSS,
</figcaption>
</figure>
</div>
</section>
</section>
<section id="criticisms-of-mediation" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="criticisms-of-mediation"><span class="header-section-number">9.6</span> Criticisms of Mediation</h2>
<p>If we think of causality, we usually think of a process in which one thing leads to another thing, which leads to something else, and so on. This is apparent if we want to explain why we think that one phenomenon causes another (see <a href="#sec-indirecteffect" class="quarto-xref"><span>Section 9.1.2</span></a>). Mediation, however, is difficult to establish with regression analysis and, as some argue, perhaps impossible to establish.</p>
<section id="causal-order-assumed" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="causal-order-assumed"><span class="header-section-number">9.6.1</span> Causal order assumed</h3>
<p>It is paramount to note that the regression approach to mediation and path models does not tell us anything about the causal order of the variables. The causal order is purely an assumption that we make. The plausibility of the assumptions depends on how well we can justify the time order of the variables and the absence of common causes for cause-consequence pairs (see <a href="#sec-causalcriteria" class="quarto-xref"><span>Section 9.1.1</span></a>).</p>
</section>
<section id="time-order" class="level3" data-number="9.6.2">
<h3 data-number="9.6.2" class="anchored" data-anchor-id="time-order"><span class="header-section-number">9.6.2</span> Time order</h3>
<p>To establish the time order of variables, we must think about the time at which the behaviours or opinions that we measure took place. This is what matters, not the time at which we measure them. We can collect information on behaviour a long time after the fact, for example by asking respondents when they started using news sites or checking internet use logs.</p>
<p>If cause and consequence appear very closely in time, it may be difficult to argue that one variable precedes the other. This may also apply to the time at which measurement takes place. If we measure cause and consequence nearly at the same time, it can be difficult to establish the time order of the two.</p>
</section>
<section id="causality-or-underlying-construct" class="level3" data-number="9.6.3">
<h3 data-number="9.6.3" class="anchored" data-anchor-id="causality-or-underlying-construct"><span class="header-section-number">9.6.3</span> Causality or underlying construct?</h3>
<p>For causes and consequences that appear nearly simultaneously, we should take into account that the two variables may measure the same underlying construct. Think of the way we construct a scale from items: We assume that the items measure the same underlying attitude, for instance, political cynicism.</p>
<p>The indicators of a scale are correlated because they have a common cause, namely, the underlying attitude. But it does not make sense to interpret the correlation as a sign of mediation. One item does not trigger another item, and so on. A mediator must be theoretically and conceptually different from both the predictor and outcome. We have to provide arguments that they are really different.</p>
</section>
<section id="every-effect-in-a-path-model-can-be-confounded" class="level3" data-number="9.6.4">
<h3 data-number="9.6.4" class="anchored" data-anchor-id="every-effect-in-a-path-model-can-be-confounded"><span class="header-section-number">9.6.4</span> Every effect in a path model can be confounded</h3>
<p>In <a href="10-confounding.html" class="quarto-xref"><span>Chapter 8</span></a>, you learned that the estimated regression coefficients can be too small, too large, or have the wrong sign (direction) if there are confounders: variables not included in the regression model that are correlated with the predictor and outcome variable. If we analyze a path model with a series of regression models, there can be confounders for each regression model. Every estimated direct effect can be wrong. As a consequence, every indirect effect, which is the product of direct effects, can be wrong.</p>
<p>The surest way to get rid of a confounder is adding it to the regression model. In a path model, we can add a variable that we expect to be a confounder as a covariate (<a href="#sec-mediationcovariate" class="quarto-xref"><span>Section 9.3</span></a>) or as an additional mediator. If a confounder comes after the outcome variable in the causal order of the path model, it cannot be a common cause to both a predictor and the outcome variable. In this situation, the confounder can be ignored. This underlines the importance of choosing a correct causal order when we construct a path model. Unfortunately, we can never be sure about this.</p>
<p>In practice, we do not know all confounders and we cannot include all of them in our regression models. We can minimize the risk of having confounders if we use randomization in an experiment. <a href="10-confounding.html#sec-randomization" class="quarto-xref"><span>Section 8.2.2</span></a> explained how randomization of the experimental treatment variable helps to eliminate confounders for the effect of the experimental treatment (predictor variable) on the dependent variable. We expect that this effect is not confounded.</p>
<p>In a path model, a mediator also serves as a predictor, so we also have to randomize the mediator variable to get correct estimates for the causal effect of the mediator on the outcome variable. With randomized predictor and mediator variables, the direct effects are probably not confounded, so the indirect effects calculated from the direct effects are also unlikely to be confounded.</p>
<p>It is difficult to manipulate a mediator in an experiment <span class="citation" data-cites="bullock_ha_2011">(<a href="14-references.html#ref-bullock_ha_2011" role="doc-biblioref">Bullock and Ha 2011</a>)</span>. If we hypothesize, for example, that political interest mediates the effect of age on newspaper reading time, how can we assign a random level of political interest to a participant in an experiment? By the way, it will also be impossible to randomize participant age in this example.</p>
</section>
<section id="recommendations" class="level3" data-number="9.6.5">
<h3 data-number="9.6.5" class="anchored" data-anchor-id="recommendations"><span class="header-section-number">9.6.5</span> Recommendations</h3>
<p>All in all, mediation is an intuitively simple and appealing concept. Unfortunately, it is very difficult to substantiate the claim that indirect effects in path models represent mediation. Mediation assumes causal effects and causality is difficult to establish.</p>
<p>If you plan to investigate mediation:</p>
<ol type="1">
<li><p>Justify that the mediator is theoretically and conceptually different from the predictor and outcome.</p></li>
<li><p>Motivate the time order of variables in the model.</p></li>
<li><p>Include variables that are likely to confound the effects of the predictor or mediator(s) in your research project and in the regression models that you are going to estimate.</p></li>
</ol>
</section>
</section>
<section id="combining-mediation-and-moderation" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="combining-mediation-and-moderation"><span class="header-section-number">9.7</span> Combining Mediation and Moderation</h2>
<p>Mediation and moderation (Chapters <a href="08-moderation-categorical.html" class="quarto-xref"><span>Chapter 6</span></a> and <a href="09-moderation-continuous.html" class="quarto-xref"><span>Chapter 7</span></a>) can occur in the same model. For example, the effect of age on newspaper reading time mediated by interest in politics can be different for females and males. In other words, the indirect effect is different for females and males.</p>
<p>If the indirect effect is different for females and males, at least one of the two direct effects (predictor on mediator or mediator on dependent variable) must be different for females and males. In <a href="#fig-causaldiagram5" class="quarto-xref">Figure&nbsp;<span>9.12</span></a>, the direct effect of age on interest in politics is moderated and as a consequence, indirect effects including this effect are moderated. This is called <em>moderated mediation</em>. In this example, sex is the moderator and interest in politics is the mediator.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-causaldiagram5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-causaldiagram5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="11-mediation_files/figure-html/fig-causaldiagram5-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-causaldiagram5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.12: Causal diagram for interest in politics as mediator between age and newspaper reading time with sex as moderator of the effect of age on interest in politics.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Several models with more than one mediator or with moderated mediation can be estimated with PROCESS. For an overview of the models, see Appendix A in Hayes <span class="citation" data-cites="RefWorks:3873">(<a href="14-references.html#ref-RefWorks:3873" role="doc-biblioref">2013</a>)</span>. The models, however, are quite complex, so we leave them for enthusiasts.</p>
</section>
<section id="take-home-points" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="take-home-points"><span class="header-section-number">9.8</span> Take-Home Points</h2>
<ul>
<li><p>A causal or path model without causal feedback loops can be estimated as a series of regression models: one regression model for each variable that has at least one predictor in the path model.</p></li>
<li><p>Unstandardized regression coefficients, standardized regression coefficients, and correlations can be multiplied to obtain indirect effects and indirect correlations.</p></li>
<li><p>An indirect effect is a mediated effect. Variables that are at the same time predicted and predictors in an indirect effect are called <em>mediators</em>, <em>intermediary variables</em>, or <em>intervening variables</em>.</p></li>
<li><p>Statistical inference on an indirect effect—its confidence interval and significance level—requires a sampling distribution of the size of the indirect effect. This distribution can be bootstrapped with the PROCESS macro <span class="citation" data-cites="RefWorks:3873">(<a href="14-references.html#ref-RefWorks:3873" role="doc-biblioref">Hayes 2013</a>)</span>.</p></li>
<li><p>Mediation is an intuitively appealing concept but it is difficult to establish. A causal interpretation of a regression coefficient requires a clear time order between predictor, mediator, and dependent variable, a clear theoretical and conceptual difference between these three variables, and the inclusion of all variables that may confound the effects of the predictor and mediator(s) in the regression models.</p></li>
</ul>
<p>Read the little but very helpful book on the logic of causal order by James A. Davis <span class="citation" data-cites="RefWorks:1494">(<a href="14-references.html#ref-RefWorks:1494" role="doc-biblioref">1985</a>)</span> for more information on causality and correlational analysis.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bullock_ha_2011" class="csl-entry" role="listitem">
Bullock, John G., and Shang E. Ha. 2011. <span>“Mediation Analysis Is Harder Than It Looks.”</span> In <em>Cambridge Handbook of Experimental Political Science</em>, edited by James N. Druckman, Donald P. Green, James H. Kuklinski, and ArthurEditors Lupia, 508–22. <span>Cambridge University Press</span>. <a href="https://doi.org/10.1017/CBO9780511921452.035">https://doi.org/10.1017/CBO9780511921452.035</a>.
</div>
<div id="ref-RefWorks:1494" class="csl-entry" role="listitem">
Davis, James A. 1985. <em>The Logic of Causal Order</em>. Beverly Hills, CA: Sage.
</div>
<div id="ref-RefWorks:3873" class="csl-entry" role="listitem">
Hayes, Andrew F. 2013. <em>Introduction to Mediation, Moderation, and Conditional Process Analysis: A Regression-Based Approach</em>. Guilford Press.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./10-confounding.html" class="pagination-link" aria-label="Regression Analysis And Confounders">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Regression Analysis And Confounders</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./12-Appendix.html" class="pagination-link" aria-label="Appendix">
        <span class="nav-page-text">Appendix</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ShKlinkenberg/Statistical-Inference/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/ShKlinkenberg/Statistical-Inference/blob/main/11-mediation.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li><li><a href="https://github.com/ShKlinkenberg/Statistical-Inference/edit/main/11-mediation.qmd" class="toc-action"><i class="bi empty"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>